[package]
name = "VulkanRenderer"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.1"
winit = "0.30.12"
smallvec = "1.15.1"

[features]
default = ["winit/rwh_06"]
validation_layers = []
